language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0
before_script:
  - travis_retry composer self-update
  - composer validate
  - travis_retry composer install --dev --no-interaction
script:
  - php vendor/bin/phpunit -c phpunit.xml
